{
	"schema_version": "1.6.0",
	"id": "CVE-2022-28470",
	"modified": "2023-11-29T09:31:53.582955Z",
	"published": "2022-05-08T20:15:07Z",
	"aliases": [
		"GHSA-57qv-h9m7-jxfg",
		"PYSEC-2022-185"
	],
	"details": "marcador package in PyPI 0.1 through 0.13 included a code-execution backdoor.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/joajfreitas/marcador",
					"events": [
						{
							"introduced": "7d20480b072109f22af199b1c1f8303f36e73c06"
						}
					]
				}
			],
			"versions": [
				"0.5.0",
				"0.5.2",
				"0.5.3",
				"v0.1",
				"v0.2",
				"v0.3",
				"v0.4"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2022-28470.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://github.com/joajfreitas/marcador/issues/5"
		},
		{
			"type": "PACKAGE",
			"url": "https://pypi.org/project/marcador/"
		},
		{
			"type": "WEB",
			"url": "http://pypi.doubanio.com/simple/request"
		}
	]
}
